package busnes_object;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Parameters;
import page.EmailPopUp;
import page.MailList;
import page.MainPage;

public class MessageBO {

    private static final Logger LOG = LogManager.getLogger(MessageBO.class.getName());

    private WebDriver driver;
    private MainPage mainPage;
    private EmailPopUp message;
    private MailList mailList;
    private String mailTo;

    public MessageBO(WebDriver driver) {
        this.driver = driver;
        //Get receiver email address
        mailTo = System.getProperty("to");
    }

    public void writeAndDraft() {
        mainPage = new MainPage(driver);
        LOG.info("Create new message");
        mainPage.composeMessage();
        message = new EmailPopUp(driver);
        LOG.info("Type receiver email");
        message.typeReceiver(mailTo);
        LOG.info("Type message title");
        message.typeTitle("TestTitle");
        LOG.info("Type text of message");
        message.typeMessage("This message is generated by automated program. You don't need reply!");
        LOG.info("Close message");
        message.close();
    }

    public void openDraftAndSend() {
        mainPage = new MainPage(driver);
        LOG.info("Open draft messages");
        mainPage.openSnoozed();
        new WebDriverWait(driver, 15).until(d->d.getCurrentUrl().contains("draft") && ((JavascriptExecutor)d).executeScript("return document.readyState")
                .toString().equals("complete"));
        mailList = new MailList(driver);
        LOG.info("Open message from top");
        mailList.openFirst();
        new WebDriverWait(driver, 15).until(d->d.getCurrentUrl().contains("draft") && ((JavascriptExecutor)d).executeScript("return document.readyState")
                .toString().equals("complete"));
        message = new EmailPopUp(driver);
        LOG.info("Send message");
        new WebDriverWait(driver, 15).until(d->d.getCurrentUrl().contains("draft") && ((JavascriptExecutor)d).executeScript("return document.readyState")
                .toString().equals("complete"));
        message.sendMessage();
    }
}
